### ISSUE TITLE
Editor crashes on tool selection on project opening

### ISSUE THREAD

**Issue by jpooleycodes** [jpooleycodes/Mundus#52]
When first opening a project, before selecting any game objects, if you select any of the transform tools the application crashes with an NPE due to the tools trying to access currentSelection variable which is null as no object was selected yet.

example code:
` Vector3 pos = projectContext.currScene.currentSelection.getPosition(temp0);`

![image](https://user-images.githubusercontent.com/28971753/170310881-12cb83b6-bb3a-41e1-93ff-3bbaa13b4694.png)

```
[12:20][Fatal][Log] java.lang.NullPointerException
	at com.mbrlabs.mundus.editor.tools.RotateTool.scaleHandles(RotateTool.java:283)
	at com.mbrlabs.mundus.editor.tools.RotateTool.gameObjectSelected(RotateTool.java:252)
	at com.mbrlabs.mundus.editor.tools.ToolManager.activateTool(ToolManager.java:82)
	at com.mbrlabs.mundus.editor.ui.modules.MundusToolbar$9.clicked(MundusToolbar.kt:197)
```

**Comment by jpooleycodes** [comment]
Fixed with commit https://github.com/jpooleycodes/Mundus/commit/3f371929fe17b0399e7f23630d2331ac89f9c816
